-- CreateTable
CREATE TABLE "Residencia" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tipoSeguro" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "pessoa" TEXT,
    "cnpj" TEXT,
    "cpf" TEXT,
    "email" TEXT NOT NULL,
    "telefone" TEXT NOT NULL,
    "formaContato" TEXT NOT NULL,
    "cep" TEXT,
    "rua" TEXT,
    "numero" TEXT,
    "complemento" TEXT,
    "bairro" TEXT,
    "cidade" TEXT,
    "estado" TEXT,
    "tipoImovel" TEXT,
    "tipoTomador" TEXT,
    "tipoConstrucao" TEXT,
    "tipoResidencia" TEXT,
    "escritorio" TEXT,
    "comercial" TEXT,
    "condominioFechado" TEXT,
    "alarme" TEXT,
    "gradeJanelas" TEXT,
    "vigia" TEXT,
    "valorImovel" TEXT,
    "valorConteudo" TEXT,
    "seguro" TEXT NOT NULL,

    CONSTRAINT "Residencia_pkey" PRIMARY KEY ("id")
);
